commands:
  bootstrap:
    steps:
      - run:
          name: Init repository
          command: ./init.sh
      - run:
          name: Install Dependencies
          command: yarn install
  lint:
    steps:
      - run:
          name: Lint
          command: yarn lint
  build:
    steps:
      - run:
          name: Build
          command: yarn build
  test:
    steps:
      - run:
          name: Test
          command: yarn test --reporters=default --reporters=jest-junit

    ### running tests messes up with the CWD, junit reported cannot be directed to write report to a proper dir
      - run:
          name: Move Test Report
          command: |
            mkdir reports
            mv junit.xml ./reports
      - store_test_results:
          path: ./reports/
      - store_artifacts:
          path: ./reports

executors:
  default:
    docker:
      - image: circleci/node

################################################################################
# JOBS
################################################################################

version: 2.1
jobs:
  publish:
    executor: default
    steps:
      - checkout
      - bootstrap
      - lint
      - build
      - test
      - run:
          name: Release
          command: yarn semantic-release --ci
  build-test:
    executor: default
    steps:
      - checkout
      - bootstrap
      - lint
      - build
      - test

################################################################################
# WORKFLOWS
################################################################################
workflows:
  version: 2
  PR:
    jobs:
      - build-test:
          filters:
            branches:
              ignore:
                - master
                - beta
  Master:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
                - beta
